project: TransPhono

language:
  web_path: "http://svn.code.sf.net/p/cmusphinx/code/trunk/cmudict/cmudict-0.7b"
  maximum_word_length: 10
  use_features: False

dataset:
  shuffle: True
  use_plurals: False


